theme: jekyll-theme-minimal
title: ğŸ’»ğŸ‘¨â€ğŸ‘©â€ğŸ‘§ğŸ²ğŸ®ğŸ’¡
description: OlÃ¡, meu nome Ã© Dinaerte e sou um desenvolvedor SÃªnior, porÃ©m atualmente Tech Lead. 
AlÃ©m de desenvolvedor de sistemas, tambÃ©m tenho os soft skills necessÃ¡rio para lideranÃ§a.
